version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: find_housing
    ports:
      - "5433:5432" #changed port cause mine was busy
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

